version: "3"

services:
    django:
      build: .
      container_name: django
      command:
        python manage.py migrate &&
        python manage.py runserver 127.0.0.1:8000
      volumes:
        - .:/usr/src/app/
      ports:
        - "8000:8000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://127.0.0.1:6379
        - CELERY_BACKEND=redis://127.0.0.1:6379
      depends_on:
        - redis
    celery:
      build: .
      command: celery -A crypto_stock.celery worker -l INFO
      volumes:
        - .:/usr/src/app/
      depends_on:
        - redis
        - django
    redis:
      image: "redis:alpine"
